# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

def build(bld):
    obj = bld.create_ns3_program('lpwan-lora-nb', ['lorawan', 'netanim'])
    obj.source = 'lpwan-lora-nb.cc'

    obj = bld.create_ns3_program('lpwan-trancing', ['lorawan', 'netanim'])
    obj.source = 'lpwan-tracing.cc'

