# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

def build(bld):
    obj = bld.create_ns3_program('experiment', ['lorawan', 'netanim'])
    obj.source = 'experiment.cc'

#    obj = bld.create_ns3_program('lpwan-trancing', ['lorawan', 'netanim'])
#    obj.source = 'lpwan-tracing.cc'

